
development:
  adapter: redis
  url: redis://localhost:6379
test:
  adapter: async
 
production:
  adapter: redis
   url: redis://redistogo:6381f6326dac81de4fa348f718c0bda1@tarpon.redistogo.com:9489/
   channel_prefix: appname_production